//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacActionsCountControl.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FacActionsCountControl.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        internal static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        internal static string Attack {
            get {
                return ResourceManager.GetString("Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string ControlCurrent {
            get {
                return ResourceManager.GetString("ControlCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ControlNext {
            get {
                return ResourceManager.GetString("ControlNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string ControlPageTitle {
            get {
                return ResourceManager.GetString("ControlPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string ControlTime {
            get {
                return ResourceManager.GetString("ControlTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        internal static string ControlTurn {
            get {
                return ResourceManager.GetString("ControlTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action needed.
        /// </summary>
        internal static string DisplayAlertActionNeeded {
            get {
                return ResourceManager.GetString("DisplayAlertActionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string DisplayAlertContinueQuestion {
            get {
                return ResourceManager.GetString("DisplayAlertContinueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DisplayAlertNo {
            get {
                return ResourceManager.GetString("DisplayAlertNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop?.
        /// </summary>
        internal static string DisplayAlertStopQuestion {
            get {
                return ResourceManager.GetString("DisplayAlertStopQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DisplayAlertYes {
            get {
                return ResourceManager.GetString("DisplayAlertYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, no control is running. Tab on screen to start ....
        /// </summary>
        internal static string NoControlRunning {
            get {
                return ResourceManager.GetString("NoControlRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingLanguageKey {
            get {
                return ResourceManager.GetString("SettingLanguageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language..
        /// </summary>
        internal static string SettingLanguagePickerTitle {
            get {
                return ResourceManager.GetString("SettingLanguagePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell.
        /// </summary>
        internal static string Spell {
            get {
                return ResourceManager.GetString("Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon.
        /// </summary>
        internal static string Summon {
            get {
                return ResourceManager.GetString("Summon", resourceCulture);
            }
        }
    }
}
